export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  budgets: '/budgets',
  settings: '/settings',
  profile: '/profile',
  registerSuccess: '/register-success',
  forgot_password: '/forgot-password',
  callback: '/auth/google/callback',
  google_redirect: '/google-auth',
  confirmEmail: '/email/confirm/:token/:email',
  reset_password: '/reset-password/:token',
  error: '/error',
};
